# cloud-config
datasource:
  Ec2:
    strict_id: false                      # Disables strict ID matching for the EC2 datasource (AWS-specific)
ssh_pwauth: no                            # Disables password-based SSH authentication (only key-based auth allowed)
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOOi2sfahLDbJz8hSEjNVmTQuyFYJYYCbbPK5zTFHqyB YC  # Adds a specific SSH key for instance access
package_update: false                     # Disables automatic package updates upon first boot
package_upgrade: false                    # Disables automatic package upgrades upon first boot
packages:
  - nginx                                 # Installs NGINX web server package
runcmd:
  - |
    sudo tee -a /var/www/html/index.nginx-debian.html > /dev/null <<'EOF'  # Appends custom HTML content to NGINX index page
    <!doctype html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Terraform provisioned</title>
    </head>
    <body>
        <h1>Endpoints</h1>
        <p>We have just provisioned YDB. You can connect to it via: <br><b>${ydb_connect_string}</b></p>   # Placeholder for dynamically inserted YDB connection string
        <p>We have just provisioned Yandex Object Storage. You can find it here: <br><b>${bucket_domain_name}</b></p>   # Placeholder for dynamically inserted object storage domain
    </body>
    </html>
    EOF
